services:
  planarally:
    container_name: planarally
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    user: "9000"
    environment:
      - PA_BASEPATH=/
      - PA_ADMIN_USER=admin
    ports:
      - "8001:8000"
    volumes:
      - planarally_assets:/planarally/static/assets
      - planarally_data:/planarally/data
      - planarally_temp:/planarally/static/temp
    networks:
      - planarally-net

volumes:
  planarally_assets:
  planarally_data:
  planarally_temp:

networks:
  planarally-net:
    driver: bridge
