# PlanarAlly - Docker Compose base
# Uso: docker compose up -d
# Documentazione: https://www.planarally.io

services:
  planarally:
    container_name: planarally
    build:
      context: .
      dockerfile: Dockerfile
    image: planarally:local
    restart: unless-stopped
    user: "9000"
    environment:
      - PA_BASEPATH=/
      - PA_ADMIN_USER=admin
    ports:
      - "8000:8000"
    volumes:
      - planarally_assets:/planarally/static/assets
      - planarally_data:/planarally/data
      - planarally_temp:/planarally/static/temp
    networks:
      - planarally-net
    command: uv run planarally.py
    entrypoint: /usr/bin/dumb-init --

volumes:
  planarally_assets:
  planarally_data:
  planarally_temp:

networks:
  planarally-net:
    driver: bridge
