[extension]
id = "quintaedizione.online"
name = "Quinta Edizione"
version = "1.0.0"
description = "Knowledge base con tutte le informazioni della 5a edizione 2024 da quintaedizione.online"
author = "McCoy88f"
